output_path: 'C:\Users\shobhita\Desktop\repos\dbb_interfaces\mqtt_cfs'

topics: 
  - 'lfs/xml'

lfs/xml: 
  key: 'value'
  key2: 'value2'

# expected message dictionary keys in the payload
message_dict:
  - 'name'
  - 'timestamp'
  - 'file'