output_path: '/home/mfi/repos/dbb_interfaces/test'

topics: 
  - 'topic_name'
  - 'lfs/json'
  - 'lfs/xml'
  - 'ros_mqtt_lfs/audio'

# generally expected message dictionary keys in the payload
message_dict:
  - 'name'
  - 'timestamp'
  - 'file'

ros_mqtt_lfs/audio:
  topic: 'ros_mqtt_lfs/audio'
  type: 'sounddevice_ros/AudioData'
  message_dict_keys: ['audio_info', 'config', 'start_time', 'audio_data']