experiment_class: 'untitled'
stream_rate: 1  # affects streamer initialization only. 

devices:
  yk_architect:
    # topics: [fts, robot_status, joints_6dof]
    namespace: yk_architect
    rostopics: [fts]
    attributes:
      description: Architect - Yaskawa GP4 Robot System
      type: Robot
      version: 0.01
      # experiment_class: 'wp-place-01'
  yk_builder:
    # topics: [fts, robot_status, joints_6dof, audio_max_freq]
    namespace: yk_builder
    rostopics: [fts]
    attributes:
      description: Builder - Yaskawa GP4 Robot System
      type: Robot
      version: 0.01
      # experiment_class: 'wp-place-01'
  yk_creator:
    # topics: [fts, robot_status, joints_6dof, audio_max_freq]
    namespace: yk_creator
    rostopics: [fts]
    attributes:
      description: Creator - Yaskawa GP4 Robot System
      type: Robot
      version: 0.01
      # experiment_class: 'wp-place-01'
  yk_destroyer:
    # topics: [fts, robot_status, joints_6dof]
    namespace: yk_destroyer
    rostopics: [fts]
    attributes:
      description: Destroyer - Yaskawa GP4 Robot System
      type: Robot
      version: 0.01
      # experiment_class: 'wp-place-01'
