watch_dir: ['/home/mfi/repos/dbb_interfaces/data']

experiment_class: 'wp-place-01'

# expected message dictionary keys in the payload
message_dict:
  - 'name'
  # - 'timestamp'
  - 'file'
  - 'experiment_class'