ros_websocket:
  host: 'localhost'
  port: 9090

ros_topics:
  /yk_creator/audio:
    name: '/yk_creator/audio'
    type: 'sounddevice_ros/AudioData'
    audio_info_topic: '/yk_creator/audio_info'
    fileprefix: 'nist_rtc_ykc_mic1'
    fileext: 'wav'
    duration_min: 1
    audio_features: ['rms', 'zcr', 'max_freq']
    audio_feature_topics: ['yk_creator/rms', 'yk_creator/zcr', 'yk_creator/max_freq']
    mqtt_topic: 'ros_mqtt_lfs/audio'
    mqtt_dict_keys: ['audio_info', 'config', 'start_time', 'audio_data']
    keep_log: False

  /yk_builder/audio:
    name: '/yk_builder/audio'
    type: 'sounddevice_ros/AudioData'
    audio_info_topic: '/yk_builder/audio_info'
    fileprefix: 'nist_rtc_ykb_mic1'
    fileext: 'wav'
    duration_min: 1
    audio_features: ['rms', 'zcr', 'max_freq']
    audio_feature_topics: ['yk_builder/rms', 'yk_builder/zcr', 'yk_builder/max_freq']
    mqtt_topic: 'ros_mqtt_lfs/audio'
    mqtt_dict_keys: ['audio_info', 'config', 'start_time', 'audio_data']
    keep_log: False

  /camera/depth/color/points:
    name: '/camera/depth/color/points'
    type: 'sensor_msgs/PointCloud2'
    fileprefix: 'nist_rtc_ykb_rs'
    fileext: 'ply'
    mqtt_topic: 'ros_mqtt_lfs/pointcloud'
    mqtt_dict_keys: ['config', 'timestamp', 'points']
    keep_log: False

  /camera/color/image_raw:
    name: '/camera/color/image_raw'
    type: 'sensor_msgs/Image'
    fileprefix: 'nist_rtc_ykb_rs'
    fileext: 'png'
    mqtt_topic: 'ros_mqtt_lfs/image'
    mqtt_dict_keys: ['config', 'timestamp', 'data']
    keep_log: False

  /yk_creator/wrist_camera/color/image_raw:
    name: '/yk_creator/wrist_camera/color/image_raw'
    type: 'sensor_msgs/Image'
    fileprefix: 'nist_rtc_ykc_wrist'
    fileext: 'png'
    mqtt_topic: 'ros_mqtt_lfs/image'
    mqtt_dict_keys: ['config', 'timestamp', 'data']
    keep_log: False

  /yk_creator/side_camera/color/image_cropped:
    name: '/yk_creator/side_camera/color/image_cropped'
    type: 'sensor_msgs/Image'
    fileprefix: 'nist_rtc_ykc_side'
    fileext: 'png'
    mqtt_topic: 'ros_mqtt_lfs/image'
    mqtt_dict_keys: ['config', 'timestamp', 'data']
    keep_log: False