output_path: '/home/mfi/repos/dbb_interfaces/test'

topics: 
  - 'topic_name'
  - 'lfs/json'
  - 'lfs/xml'
  - 'ros_mqtt_lfs/audio'
  - 'ros_mqtt_lfs/pointcloud'
  - 'lfs/ply'
  - 'ros_mqtt_lfs/image'

# generally expected message dictionary keys in the payload
message_dict:
  - 'name'
  - 'timestamp'
  - 'file'

ros_mqtt_lfs/audio:
  topic: 'ros_mqtt_lfs/audio'
  type: 'sounddevice_ros/AudioData'
  message_dict_keys: ['audio_info', 'config', 'start_time', 'audio_data']

ros_mqtt_lfs/pointcloud:
  topic: 'ros_mqtt_lfs/pointcloud'
  type: 'sensor_msgs/PointCloud2'
  message_dict_keys: ['config', 'timestamp', 'points']

ros_mqtt_lfs/image:
  topic: 'ros_mqtt_lfs/image'
  type: 'sensor_msgs/Image'
  message_dict_keys: ['config', 'timestamp', 'data']